{% set name = "napari-3d-ortho-viewer" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-3d-ortho-viewer-{{ version }}.tar.gz
  sha256: 2ec8a3eb33f5ddcb4054203d44734800228526ed4e6581904d09ac3b83a33aee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - scikit-image
    - qtpy

test:
  imports:
    - napari_3d_ortho_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-3d-ortho-viewer
  summary: Napari 3D Ortho Viewer - an ortho viewer for napari for 3D images
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/gatoniel/napari-3d-ortho-viewer

extra:
  recipe-maintainers:
    - gatoniel
    - goanpeca
    - jaimergp
